[package]
name = "robius-demo-simple"
version = "0.1.0"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
edition = "2021"
description = "Simple demo of Robius platform abstraction crates from a Makepad app"
license = "MIT OR Apache-2.0"

[dependencies]
makepad-widgets = { git = "https://github.com/makepad/makepad", branch = "rik" }

robius-authentication = { git = "https://github.com/project-robius/robius-authentication" } 
robius-open = { git = "https://github.com/project-robius/robius-open" } 
